import { View as RNView} from 'react-native';

const View = ({
        children,
        w,
        h,
        position,
        left,
        right,
        top,
        bottom,
        flex,
        flexDirection,
        flexGrow,
        alignItems,
        justifyContent,
        alignSelf,
        columnGap,
        rowGap,
        pl,
        pr,
        pt,
        pb,
        pv,
        ph,
        ml,
        mr,
        mt,
        mb,
        mv,
        mh,
        borderWidth,
        borderTopWidth,
        borderBottomWidth,
        borderRadius,
        borderColor,
        backgroundColor,
        style,
    }) => {

    return (
        <RNView style={[
            {width: w},
            {height: h},
            {position: position},
            {left: left},
            {right: right},
            {Top: top},
            {bottom: bottom},
            {flex: flex},
            {flexDirection: flexDirection},
            {flexGrow: flexGrow},
            {alignItems: alignItems},
            {justifyContent: justifyContent},
            {alignSelf: alignSelf},
            {columnGap: columnGap},
            {rowGap: rowGap},
            {paddingLeft: pl},
            {paddingRight: pr},
            {paddingTop: pt},
            {paddingBottom: pb},
            {paddingVertical: pv},
            {paddingHorizontal: ph},
            {marginLeft: ml},
            {marginRight: mr},
            {marginTop: mt},
            {marginBottom: mb},
            {marginVertical: mv},
            {marginHorizontal: mh},
            {borderWidth: borderWidth},
            {borderTopWidth: borderTopWidth},
            {borderBottomWidth: borderBottomWidth},
            {borderRadius: borderRadius},
            {borderColor: borderColor},
            {backgroundColor: backgroundColor},
            style,
        ]}>
            {children}
        </RNView>
    );
};

export default View;
